### PR TITLE
Auto Updating Fix/Enchancement

### PR DESCRIPTION
**Pull request by DomGrieco**
Ouroboros was not configured to monitor and update any containers. This PR add's an option to the PG-Apps menu (5) to configure ouroboros auto updater. After choosing apps to auto update, ouroboros is rebuilt with the apps specified included into the monitor variable.

### CODE REVIEW

**Comment by thesammykins** [comment]
This all appears to be kosher here, need one more to check over for any issues I may have glanced over. 

I assume you've confirmed all good on your build @DomGrieco as you didn't mention this in the commit comments?

**Comment by DomGrieco** [comment]
Made some additional changes to update playbook and store monitor variables in a unique file to the updater (not shared with pgbox)

**Comment by Hawkinzzz** [comment]
Looks much better! Happy for it to be merged.

**Comment by DomGrieco** [comment]
@thesammykins I've tested this in my build quite a bit. Merging!

**Pull request merged**
